# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ra_10_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ra_10_controller:
  ros__parameters:
    joints:
      - Revolute 1
      - Revolute 2
      - Revolute 3
      - Revolute 4
      - Revolute 5
      - Revolute 6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true